@startuml
actor "ClienteVip" as pasajero

rectangle "Sistema de Reservas Aéreas" {
    usecase RealizarReserva
    (AplicarDescuentoVip)
}

pasajero --> (RealizarReserva)

(AplicarDescuentoVip) ..> (RealizarReserva) : <<extend>>\n[Cliente es VIP]

@enduml