@startuml
actor "ClienteVip" as pasajero


package "Sistema de Reservas Aéreas" {
  usecase UC1 as "RealizarReserva
  --
  Punto de extensión
  Establecer clase
  de asiento"
  useCase UC2 as "AplicarDescuentoVip"
}

pasajero --> UC1

UC2 .down.> UC1 : <<extend>>\n[Cliente es VIP]

left to right direction

@enduml